name: "Build & Push"

on:
  push:
    branches: "probing-gh-actions"

jobs:
  build_push_image:
    name: ${{ matrix.image_name }}
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: probing-api
            dockerfile_path: packages/probing-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: normalize branch name for tagging
        run: |
          NORM_TAG=$(echo "$GITHUB_REF_NAME" | tr -s "/" "-")
          echo "NORM_TAG=$NORM_TAG" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ${{ matrix.dockerfile_path }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.NORM_TAG }}
